on: [push, pull_request, workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
    with:
      # 빌드할 보드 이름을 여기에 적어줘야 에러가 나지 않습니다.
      build_matrix_path: "build.yaml"
